# Xargo.toml
#
# Uses Xargo to build a local copy of Rust's libstd optimized for size, which
# allows for better LTO optimization in the final Ossuary release library.
# Doing this shaves about 100KB off of the shared lib.
#
# 'cargo install xargo' and 'rustup component add rust-src' if you need it.
# Only works with nightly.
#
[dependencies]
std = {default-features=false, features=["panic_immediate_abort"] }
