# Xargo.toml
#
# Uses Xargo to build a local copy of Rust's libstd optimized for size, which
# allows for better LTO optimization in the final Ossuary release library.
# Doing this shaves about 100KB off of the shared lib.
#
# 'cargo install xargo' and 'rustup component add rust-src' if you need it.
# Only works with nightly.
#
[dependencies]
std = {default-features=false, features=["panic_immediate_abort"]}

[profile.release]
panic = "abort"
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = true
overflow-checks = false
